/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Article/src/Article.vue')['default']
    BaseInfo: typeof import('./src/components/BaseInfo/src/BaseInfo.vue')['default']
    DigitalClock: typeof import('./src/components/DigitalClock/src/DigitalClock.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDvider: typeof import('element-plus/es')['ElDvider']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FeelingCard: typeof import('./src/components/Feeling/src/FeelingCard.vue')['default']
    MessageCard: typeof import('./src/components/MessageCard/src/MessageCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineCard: typeof import('./src/components/TimelineCard/src/TimelineCard.vue')['default']
  }
}
